### ISSUE TITLE
Detect if runtime is installed before download

### ISSUE THREAD

**Issue by kdblocher** [ronaldbosma/InstallNetCoreRuntimeAndHostingTask#3]
Great task. Worked like a charm right out of the box!

It takes about 30-45 seconds and quite a bit of bandwidth to download the installer. For a continuous deployment pipeline this is a bit expensive, especially when the target environment probably is already configured correctly.

I think it would be worth checking if the desired runtime version is already installed before downloading the installer. You could also add a boolean parameter "force" to always download and run the installer regardless.

Thanks

**Comment by ronaldbosma** [comment]
Thanks for the feedback.

Do you know a good way to check if the .NET Core hosting bundle is installed? I've looked at `dotnet --info` but it only lists the SDK and runtime. Not if the hosting bundle is installed.

**Comment by JonnyG365** [comment]
all I have been able to find so far is this registry key HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Updates\.NET Core

**Comment by kdblocher** [comment]
Try this - will return `true` if it finds it in the registry
`(Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | % { $_.DisplayName } | Where { $_ -Match 'Microsoft ASP.NET Core Module V2' }).Count -gt 0`

**Comment by Jetski5822** [comment]
This would be awesome!! +1

**Comment by kdblocher** [comment]
I've forked it at https://github.com/wagner-machine/InstallNetCoreRuntimeAndHostingTask and will take a look.

**Comment by JonnyG365** [comment]
@kdblocher don't suppose this suggested improvement is able to make any progress. We love using this task but it's a bit of a blunt instrument in the every time you run a CI pipeline doing a fresh install without checking if you already have the latest version.

**Comment by JonnyG365** [comment]
@kdblocher don't suppose this suggested improvement is able to make any progress. We love using this task but it's a bit of a blunt instrument in the every time you run a CI pipeline doing a fresh install without checking if you already have the latest version.

**Comment by ronaldbosma** [comment]
Hi @JonnyG365. Thanks for putting this issue on my radar again. Because you can use [Microsoft Update](https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/) now to update .NET Core I've decided to not add any major enhancement like this request.

**Comment by kdblocher** [comment]
@ronaldbosma it doesn't appear that Microsoft Update supports CI/CD scenarios, rather just an automatic update experience. For those who need to support arbitrary versions of .NET Core, or don't want to allow automatic updates of this kind, it's not a good solution.

@JonnyG365, as you can see, @ronaldbosma sat on this issue for a year with no response. I may try to get a forked copy working with this feature.

**Comment by JonnyG365** [comment]
@kdblocher I assume you have a similar use case to us I want to be able to add this kind of task to the build pipeline and have it download/install/update if needed but do nothing if you are already running the version specified
