### ISSUE TITLE
installing net core runtime in Remote Machine

### ISSUE THREAD

**Issue by joaodotnet** [ronaldbosma/InstallNetCoreRuntimeAndHostingTask#4]
What about installing the net core runtime and hosting in a remote machine?
Do you think is possible?
I don't use Environments with Virtual Machines.
I deploy a net core app with WINRM - IIS Web App Manage/Deploy task.

**Comment by ronaldbosma** [comment]
Hi @joaoGoncalves81. It's not possible with the current task because it runs the PowerShell script locally on the machine. The PowerShell script itself could probably be reused though for a version that works on a remote machine.
